pl:
  kocan:
    springframeworkdevopsonaws:
      profile:
        message: This is my QA profile
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springguru
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update


